apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq
  labels:
    node: rabbitmq
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    path: /home/rabbitmq
    server: 172.16.1.210
