apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-0
  labels:
    node: rabbitmq
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs
