apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  labels:
    app: rabbitmq
spec:
  type: NodePort
  ports:
  - port: 5672
    targetPort: 5672
    nodePort: 30402
    name: my-port
  - port: 15672
    targetPort: 15672
    nodePort: 30403
    name: manage
#  clusterIP: None
  selector:
    app: rabbitmq

